jms_serializer:
    property_naming:
        id: jms_serializer.identical_property_naming_strategy
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    default_context:
        serialization:
            serialize_null: true
        deserialization:
            serialize_null: false
    metadata:
        auto_detection: false
        directories:
            Proxy:
                namespace_prefix: App\Dto\Exchange
                path: "%kernel.project_dir%/config/Dto/Exchange"
            Entity:
                namespace_prefix: App\Entity
                path: "%kernel.project_dir%/config/Dto/Entity"

when@prod:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
